version: '2'
services:
    obrasprivadas4-app:
        image: obrasprivadas4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://obrasprivadas4-mysql:3306/obrasprivadas4?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    obrasprivadas4-mysql:
        extends:
            file: mysql.yml
            service: obrasprivadas4-mysql
